Repository revealin/mobile-app, pull requests merged in 2019-12, with the labels that each got.

#1 initial commit
  .buckconfig
  .eslintrc.js
  .flowconfig
  .gitattributes
  .gitignore
  .prettierrc.js
  .watchmanconfig
  App.tsx
  __tests__/App-test.tsx
  android/app/BUCK
  android/app/build.gradle
  android/app/build_defs.bzl
  android/app/debug.keystore
  android/app/proguard-rules.pro
  android/app/src/debug/AndroidManifest.xml
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/mobileapp/MainActivity.java
  android/app/src/main/java/com/mobileapp/MainApplication.java
  android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  android/app/src/main/res/values/strings.xml
  android/app/src/main/res/values/styles.xml
  android/build.gradle
  android/gradle.properties
  android/gradle/wrapper/gradle-wrapper.jar
  android/gradle/wrapper/gradle-wrapper.properties
  android/gradlew
  android/gradlew.bat
  android/settings.gradle
  app.json
  babel.config.js
  index.js
  ios/Podfile
  ios/mobileapp-tvOS/Info.plist
  ios/mobileapp-tvOSTests/Info.plist
  ios/mobileapp.xcodeproj/project.pbxproj
  ios/mobileapp.xcodeproj/xcshareddata/xcschemes/mobileapp-tvOS.xcscheme
  ios/mobileapp.xcodeproj/xcshareddata/xcschemes/mobileapp.xcscheme
  ios/mobileapp/AppDelegate.h
  ios/mobileapp/AppDelegate.m
  ios/mobileapp/Base.lproj/LaunchScreen.xib
  ios/mobileapp/Images.xcassets/AppIcon.appiconset/Contents.json
  ios/mobileapp/Images.xcassets/Contents.json
  ios/mobileapp/Info.plist
  ios/mobileapp/main.m
  ios/mobileappTests/Info.plist
  ios/mobileappTests/mobileappTests.m
  metro.config.js
  package.json
  rn-cli.config.js
  tsconfig.json
  yarn.lock
Labels: Feature

#2 Page connection/insciption
  App.tsx
  package-lock.json
  src/features/authentication/authentication.tsx
  src/styles/authentication/style.tsx
Labels: Feature

#3 Features Authentication
  App.tsx
  src/features/authentication/authentication.tsx
  src/styles/authentication/style.tsx
  src/styles/style.tsx
Labels: Bug fix, Feature

#5 Implement basic routing and updateprofile page WYP
  App.tsx
  android/app/src/main/AndroidManifest.xml
  package-lock.json
  package.json
  src/features/authentication/connexion.tsx
  src/features/authentication/home.tsx
  src/features/authentication/inscription.tsx
  src/features/userProfile/modifyUserProfile.tsx
  src/features/userProfile/userProfile.tsx
  src/navigation/mainRouter.tsx
  src/styles/authentication/style.tsx
  src/styles/style.tsx
  src/styles/userProfile/style.tsx
Labels: Bug fix, Feature

#6 Design authentication profil
  package-lock.json
  package.json
  src/features/authentication/connexion.tsx
  src/features/authentication/home.tsx
  src/features/authentication/inscription.tsx
  src/styles/style.tsx
  yarn.lock
Labels: Feature, Optimization

#7 Many update design
  src/features/authentication/connexion.tsx
  src/features/authentication/home.tsx
  src/features/authentication/inscription.tsx
  src/styles/style.tsx
Labels: Optimization

#8 Toujours du design
  src/features/authentication/inscription.tsx
  src/styles/style.tsx
Labels: Feature

#9 Implements SwipePage and part of it's logic
  package-lock.json
  package.json
  src/features/swipe/swipe.tsx
  src/features/userProfile/modifyUserProfile.tsx
  src/navigation/mainRouter.tsx
  src/shared/components/description.tsx
  src/styles/style.tsx
  src/styles/swipe/style.tsx
  src/styles/userProfile/style.tsx
  tsconfig.json
Labels: Feature

#10 Fix navigation issues
  src/features/authentication/connexion.tsx
  src/features/authentication/home.tsx
  src/features/authentication/inscription.tsx
Labels: Bug fix
